---
code:
    py_core:
        - Sites/Bio/ebscore/code/py  # has to be an absolute path to external code base
    R_core: # 
        Sites/projectsceleton/code/R:
            - config_decorate.R
    # shell_core:
    #     - Sites/Bio/ebscore/shell
    threads: 6
    java:
        mem: 8g
paths:
    static: Dropbox/Icke/Work/static/hg38  # absolute or relative to HOME
    base: Dropbox/Icke/Work/LO/LOBioinfo/PanelSeq # absolute or relative to HOME / used as relative base for below folders
    Data: data
        Original: 
            pPCR: pPCR.csv
        RData:
            RData/RNAseq
    Results:
        img: img
        tables: table
        reports: html
    info_path: info
load_and_save:  # here are the configs for the "load_and_save function"
    verbose: False
    read_lines: 10
simple_message:
    run: True
    data:
        - 23
        - 40
        - 50
    message: Hello
