---
code:
    py_core:
        - Sites/Bio/ebscore/code/py  # has to be an absolute path to external code base
    R_core: # 
        Sites/projectsceleton/code/R:
            - config_decorate.R
    # shell_core:
    #     - Sites/Bio/ebscore/shell
    threads: 6
    java:
        mem: 8g
paths:
    data_path: data
    static_path: Work/static/hg38
    base_path: Dropbox/Icke/Work/LO/LOBioinfo/PanelSeq
    output_path: output
    info_path: info
    img_path: output/img
    tables_path: output/tables
load_and_save:  # here are the configs for the "load_and_save function"
    verbose: False
    read_lines: 10
simple_message:
    run: True
    data:
        - 23
        - 40
        - 50
    message: Hello
